# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kservice': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/ksolid': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kfilemetadata': '@stable'
    'frameworks/kthreadweaver': '@stable'
    'frameworks/knotifyconfig': '@stable'
    'frameworks/knotifications': '@stable'
