#!/usr/bin/perl

# Copyright (c) 2008-2022 by Gilles Caulier, <caulier dot gilles at gmail dot com>
#
# SPDX-License-Identifier: BSD-3-Clause

system("perl ./gits populate");

if ( $? > 0 )
{
    print "$ : Failed to populate gits repositories, aborting.\n";
    exit (-1);
}

exit (0);
