/* ============================================================
 *
 * This file is a part of digiKam project
 * https://www.digikam.org
 *
 * Date        : 2005-11-06
 * Description : list of RAW file extensions supported by libraw
 *
 * Copyright (C) 2005-2019 by Gilles Caulier <caulier dot gilles at gmail dot com>
 *
 * This program is free software; you can redistribute it
 * and/or modify it under the terms of the GNU General
 * Public License as published by the Free Software Foundation;
 * either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * ============================================================ */

#include "drawfiles.h"

namespace Digikam
{

QString s_rawFileExtentions()
{
    QList<QString> list = s_rawFileExtensionsdWithDesc().keys();
    QString ret;

    foreach (const QString& mime, list)
    {
        ret.append(QString::fromLatin1("*.%1 ").arg(mime));
    }

    return ret;
}

QMap<QString, QString> s_rawFileExtensionsdWithDesc()
{
    QMap<QString, QString> map;
    // NOTE: extension list Version 1 and 2 are taken from http://www.cybercom.net/~dcoffin/dcraw/rawphoto.c

    //                        Ext                   Descriptions From
    //                                              www.file-extensions.org
    //                                              en.wikipedia.org/wiki/RAW_file_format
    //                                              filext.com


    // NOTE: VERSION 1
    map.insert(QLatin1String("bay"),  QLatin1String("Casio Digital Camera Raw File Format"));
    map.insert(QLatin1String("bmq"),  QLatin1String("NuCore Raw Image File"));

    map.insert(QLatin1String("cr2"),  QLatin1String("Canon Digital Camera RAW Image Format version 2.0")); // These images are based on the TIFF image standard.

    map.insert(QLatin1String("crw"),  QLatin1String("Canon Digital Camera RAW Image Format version 1.0"));
    map.insert(QLatin1String("cs1"),  QLatin1String("Capture Shop Raw Image File"));
    map.insert(QLatin1String("dc2"),  QLatin1String("Kodak DC25 Digital Camera File"));

    map.insert(QLatin1String("dcr"),  QLatin1String("Kodak Digital Camera Raw Image Format")); // for these models: Kodak DSC Pro SLR/c, Kodak DSC Pro SLR/n, Kodak DSC Pro 14N, Kodak DSC PRO 14nx.

    map.insert(QLatin1String("dng"),  QLatin1String("Adobe Digital Negative")); // DNG is publicly available archival format for the raw files generated by digital cameras. By addressing the lack of an open standard for the raw files created by individual camera models, DNG helps ensure that photographers will be able to access their files in the future.

    map.insert(QLatin1String("erf"),  QLatin1String("Epson Digital Camera Raw Image Format"));
    map.insert(QLatin1String("fff"),  QLatin1String("Imacon Digital Camera Raw Image Format"));
    map.insert(QLatin1String("hdr"),  QLatin1String("Leaf Raw Image File"));
    map.insert(QLatin1String("k25"),  QLatin1String("Kodak DC25 Digital Camera Raw Image Format"));
    map.insert(QLatin1String("kdc"),  QLatin1String("Kodak Digital Camera Raw Image Format"));
    map.insert(QLatin1String("mdc"),  QLatin1String("Minolta RD175 Digital Camera Raw Image Format"));
    map.insert(QLatin1String("mos"),  QLatin1String("Mamiya Digital Camera Raw Image Format"));
    map.insert(QLatin1String("mrw"),  QLatin1String("Minolta Dimage Digital Camera Raw Image Format"));
    map.insert(QLatin1String("nef"),  QLatin1String("Nikon Digital Camera Raw Image Format"));
    map.insert(QLatin1String("orf"),  QLatin1String("Olympus Digital Camera Raw Image Format"));
    map.insert(QLatin1String("pef"),  QLatin1String("Pentax Digital Camera Raw Image Format"));
    map.insert(QLatin1String("pxn"),  QLatin1String("Logitech Digital Camera Raw Image Format"));
    map.insert(QLatin1String("raf"),  QLatin1String("Fuji Digital Camera Raw Image Format"));
    map.insert(QLatin1String("raw"),  QLatin1String("Panasonic Digital Camera Image Format"));
    map.insert(QLatin1String("rdc"),  QLatin1String("Digital Foto Maker Raw Image File"));
    map.insert(QLatin1String("sr2"),  QLatin1String("Sony Digital Camera Raw Image Format"));
    map.insert(QLatin1String("srf"),  QLatin1String("Sony Digital Camera Raw Image Format")); // for DSC-F828 8 megapixel digital camera or Sony DSC-R1
    map.insert(QLatin1String("x3f"),  QLatin1String("Sigma Digital Camera Raw Image Format")); // for devices based on Foveon X3 direct image sensor.
    map.insert(QLatin1String("arw"),  QLatin1String("Sony Digital Camera Raw Image Format")); // for Alpha devices.

    // NOTE: VERSION 2

    map.insert(QLatin1String("3fr"),  QLatin1String("Hasselblad Digital Camera Raw Image Format"));
    map.insert(QLatin1String("cine"), QLatin1String("Phantom Software Raw Image File"));
    map.insert(QLatin1String("ia"),   QLatin1String("Sinar Raw Image File"));
    map.insert(QLatin1String("kc2"),  QLatin1String("Kodak DCS200 Digital Camera Raw Image Format"));
    map.insert(QLatin1String("mef"),  QLatin1String("Mamiya Digital Camera Raw Image Format"));
    map.insert(QLatin1String("nrw"),  QLatin1String("Nikon Digital Camera Raw Image Format"));
    map.insert(QLatin1String("qtk"),  QLatin1String("Apple Quicktake 100/150 Digital Camera Raw Image Format"));
    map.insert(QLatin1String("rw2"),  QLatin1String("Panasonic LX3 Digital Camera Raw Image Format"));
    map.insert(QLatin1String("sti"),  QLatin1String("Sinar Capture Shop Raw Image File"));

    // NOTE: VERSION 3

    map.insert(QLatin1String("rwl"),  QLatin1String("Leica Digital Camera Raw Image Format"));

    // NOTE: VERSION 4

    map.insert(QLatin1String("srw"),  QLatin1String("Samnsung Raw Image Format"));

/*
    TODO: check if these format are supported

    map.insert(QLatin1String("drf"),  QLatin1String("Kodak Digital Camera Raw Image Format"));
    map.insert(QLatin1String("dsc"),  QLatin1String("Kodak Digital Camera Raw Image Format"));
    map.insert(QLatin1String("ptx"),  QLatin1String("Pentax Digital Camera Raw Image Format"));
    map.insert(QLatin1String("cap"),  QLatin1String("Phase One Digital Camera Raw Image Format"));
    map.insert(QLatin1String("iiq"),  QLatin1String("Phase One Digital Camera Raw Image Format"));
    map.insert(QLatin1String("rwz"),  QLatin1String("Rawzor Digital Camera Raw Image Format"));
*/

    return map;
}

int s_rawFileExtensionsVersion()
{
    // NOTE: increment this number whenever you change the above string
    return 4;
}

} // namespace Digikam
