/* ============================================================
 *
 * This file is a part of digiKam project
 * https://www.digikam.org
 *
 * Date        : 2009-08-03
 * Description : digiKam export headers
 *
 * NOTE: Only use pure C comments here as this header is shared between C and C++
 *
 * SPDX-FileCopyrightText: 2009-2024 by Gilles Caulier <caulier dot gilles at gmail dot com>
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 * ============================================================ */

#pragma once

/**
 * These header files automatically generated by generate_export_header() macro
 * for each shared library targets.
 */
#include "digikam_core_export.h"
#include "digikam_database_export.h"
#include "digikam_gui_export.h"
