/* ============================================================
 *
 * This file is a part of digiKam project
 * https://www.digikam.org
 *
 * Date        : 2009-06-15
 * Description : multi-languages string editor
 *
 * SPDX-FileCopyrightText: 2009-2022 by Gilles Caulier <caulier dot gilles at gmail dot com>
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 * ============================================================ */

#include "altlangstredit_p.h"

namespace Digikam
{

/**
 * NOTE: We cannot use KLocale::allLanguagesList() here because KDE only
 * support 2 characters country codes. XMP require 2+2 characters language+country
 * following RFC 3066.
 * The format is based on xx-XX using ISO-639 two-letter code with ISO-3166 two-letter country code.
 *
 * List version 1       : babelwiki.babelzilla.org/index.php?title=Language_codes
 * List version 2 update: xml.coverpages.org/TexinUsingLangID.html
 * List version 3 update: List of ISO 639-1 codes (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
 *                        List of ISO 639-2 codes (https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes)
 *                        List of ISO 639 macrolanguage (https://en.wikipedia.org/wiki/ISO_639_macrolanguage)
 *
 * NOTE: this lists of RFC3066 map is also used un conversion map from DOnlineTranslator class.
 *       Any changes here must be also backported to DOnlineTranslator class.
 */
const LanguageCodeMap s_rfc3066ForXMP =
{
    // The first one from the list is the Default Language code specified by XMP paper.

    { QLatin1String("x-default"), xi18nc("@info: country code", "Default Language")                                                },

    // the rest follow the RFC 3066.

    { QLatin1String("af-ZA"),     xi18nc("@info: country code", "Afrikaans (South Africa)")                                        },
    { QLatin1String("am-ET"),     xi18nc("@info: country code", "Amharic (Ethiopia)")                                              },
    { QLatin1String("apc-TR"),    xi18nc("@info: country code", "North Levantine Arabic (Turkey)")                                 },
    { QLatin1String("ar-AE"),     xi18nc("@info: country code", "Arabic (UAE)")                                                    },
    { QLatin1String("ar-BH"),     xi18nc("@info: country code", "Arabic (Bahrain)")                                                },
    { QLatin1String("ar-DZ"),     xi18nc("@info: country code", "Arabic (Algeria)")                                                },
    { QLatin1String("ar-EG"),     xi18nc("@info: country code", "Arabic (Egypt)")                                                  },
    { QLatin1String("ar-IQ"),     xi18nc("@info: country code", "Arabic (Iraq)")                                                   },
    { QLatin1String("ar-IL"),     xi18nc("@info: country code", "Arabic (Israel)")                                                 },
    { QLatin1String("ar-JO"),     xi18nc("@info: country code", "Arabic (Jordan)")                                                 },
    { QLatin1String("ar-KW"),     xi18nc("@info: country code", "Arabic (Kuwait)")                                                 },
    { QLatin1String("ar-LB"),     xi18nc("@info: country code", "Arabic (Lebanon)")                                                },
    { QLatin1String("ar-LY"),     xi18nc("@info: country code", "Arabic (Libya)")                                                  },
    { QLatin1String("ar-MA"),     xi18nc("@info: country code", "Arabic (Morocco)")                                                },
    { QLatin1String("ar-MR"),     xi18nc("@info: country code", "Arabic (Mauritania)")                                             },
    { QLatin1String("ar-PS"),     xi18nc("@info: country code", "Arabic (Palestinian West Bank and Gaza)")                         },
    { QLatin1String("ar-OM"),     xi18nc("@info: country code", "Arabic (Oman)")                                                   },
    { QLatin1String("ar-QA"),     xi18nc("@info: country code", "Arabic (Qatar)")                                                  },
    { QLatin1String("ar-SA"),     xi18nc("@info: country code", "Arabic (Saudi Arabia)")                                           },
    { QLatin1String("ar-SD"),     xi18nc("@info: country code", "Arabic (Sudan)")                                                  },
    { QLatin1String("ar-SO"),     xi18nc("@info: country code", "Arabic (Somalia)")                                                },
    { QLatin1String("ar-SY"),     xi18nc("@info: country code", "Arabic (Syria)")                                                  },
    { QLatin1String("ar-TD"),     xi18nc("@info: country code", "Arabic (Chad)")                                                   },
    { QLatin1String("ar-TN"),     xi18nc("@info: country code", "Arabic (Tunisia)")                                                },
    { QLatin1String("ar-YE"),     xi18nc("@info: country code", "Arabic (Yemen)")                                                  },
    { QLatin1String("as-IN"),     xi18nc("@info: country code", "Assamese (India)")                                                },
    { QLatin1String("az-AZ"),     xi18nc("@info: country code", "Azerbaijani (Republic of Azerbaijan)")                            },
    { QLatin1String("ba-RU"),     xi18nc("@info: country code", "Bashkir (Russia)")                                                },
    { QLatin1String("bn-BD"),     xi18nc("@info: country code", "Bengali (Bangladesh)")                                            },
    { QLatin1String("bn-IN"),     xi18nc("@info: country code", "Bengali (India)")                                                 },
    { QLatin1String("bn-SG"),     xi18nc("@info: country code", "Bengali (Singapore)")                                             },
    { QLatin1String("be-BY"),     xi18nc("@info: country code", "Belarusian (Belarus)")                                            },
    { QLatin1String("bg-BG"),     xi18nc("@info: country code", "Bulgarian (Bulgaria)")                                            },
    { QLatin1String("bn-IN"),     xi18nc("@info: country code", "Bengali (India)")                                                 },
    { QLatin1String("bo-BT"),     xi18nc("@info: country code", "Tibetan (Bhutan)")                                                },
    { QLatin1String("bo-CN"),     xi18nc("@info: country code", "Tibetan (People's Republic of China)")                            },
    { QLatin1String("br-FR"),     xi18nc("@info: country code", "Breton (France)")                                                 },
    { QLatin1String("bs-BA"),     xi18nc("@info: country code", "Bosnian (Bosnia and Herzegovina)")                                },
    { QLatin1String("bs-BG"),     xi18nc("@info: country code", "Bulgarian (Bulgaria)")                                            },
    { QLatin1String("ca-AD"),     xi18nc("@info: country code", "Catalan (Andorra)")                                               },
    { QLatin1String("ca-ES"),     xi18nc("@info: country code", "Catalan (Spain)")                                                 },
    { QLatin1String("ca-FR"),     xi18nc("@info: country code", "Catalan (France)")                                                },
    { QLatin1String("ceb-PH"),    xi18nc("@info: country code", "Cebuano (Philippines)")                                           },
    { QLatin1String("ch-GU"),     xi18nc("@info: country code", "Chamorro (Guam)")                                                 },
    { QLatin1String("ch-MP"),     xi18nc("@info: country code", "Chamorro (Northern Mariana Islands)")                             },
    { QLatin1String("co-FR"),     xi18nc("@info: country code", "Corsican (France)")                                               },
    { QLatin1String("cs-CZ"),     xi18nc("@info: country code", "Czech (Czechia)")                                                 },
    { QLatin1String("cy-GB"),     xi18nc("@info: country code", "Welsh (United Kingdom)")                                          },
    { QLatin1String("da-DK"),     xi18nc("@info: country code", "Danish (Denmark)")                                                },
    { QLatin1String("da-GL"),     xi18nc("@info: country code", "Danish (Greenland)")                                              },
    { QLatin1String("de-AT"),     xi18nc("@info: country code", "German (Austria)")                                                },
    { QLatin1String("de-CH"),     xi18nc("@info: country code", "German (Switzerland)")                                            },
    { QLatin1String("de-DE"),     xi18nc("@info: country code", "German (Germany)")                                                },
    { QLatin1String("de-DK"),     xi18nc("@info: country code", "German (Denmark)")                                                },
    { QLatin1String("de-LI"),     xi18nc("@info: country code", "German (Liechtenstein)")                                          },
    { QLatin1String("de-LU"),     xi18nc("@info: country code", "German (Luxembourg)")                                             },
    { QLatin1String("el-CY"),     xi18nc("@info: country code", "Greek (Cyprus)")                                                  },
    { QLatin1String("el-GR"),     xi18nc("@info: country code", "Greek (Greece)")                                                  },
    { QLatin1String("en-AG"),     xi18nc("@info: country code", "English (Antigua and Barbuda)")                                   },
    { QLatin1String("en-AI"),     xi18nc("@info: country code", "English (Anguilla)")                                              },
    { QLatin1String("en-AS"),     xi18nc("@info: country code", "English (American Samoa)")                                        },
    { QLatin1String("en-AU"),     xi18nc("@info: country code", "English (Australia)")                                             },
    { QLatin1String("en-BB"),     xi18nc("@info: country code", "English (Barbados)")                                              },
    { QLatin1String("en-BM"),     xi18nc("@info: country code", "English (Bermuda)")                                               },
    { QLatin1String("en-BN"),     xi18nc("@info: country code", "English (Brunei)")                                                },
    { QLatin1String("en-BS"),     xi18nc("@info: country code", "English (Bahamas)")                                               },
    { QLatin1String("en-BW"),     xi18nc("@info: country code", "English (Botswana)")                                              },
    { QLatin1String("en-BZ"),     xi18nc("@info: country code", "English (Belize)")                                                },
    { QLatin1String("en-CA"),     xi18nc("@info: country code", "English (Canada)")                                                },
    { QLatin1String("en-CB"),     xi18nc("@info: country code", "English (Caribbean)")                                             },
    { QLatin1String("en-CK"),     xi18nc("@info: country code", "English (Cook Islands)")                                          },
    { QLatin1String("en-CM"),     xi18nc("@info: country code", "English (Cameroon)")                                              },
    { QLatin1String("en-DM"),     xi18nc("@info: country code", "English (Dominica)")                                              },
    { QLatin1String("en-ER"),     xi18nc("@info: country code", "English (Eritrea)")                                               },
    { QLatin1String("en-ET"),     xi18nc("@info: country code", "English (Ethiopia)")                                              },
    { QLatin1String("en-FJ"),     xi18nc("@info: country code", "English (Fiji)")                                                  },
    { QLatin1String("en-FK"),     xi18nc("@info: country code", "English (Falkland Islands)")                                      },
    { QLatin1String("en-FM"),     xi18nc("@info: country code", "English (Micronesia)")                                            },
    { QLatin1String("en-GB"),     xi18nc("@info: country code", "English (United Kingdom)")                                        },
    { QLatin1String("en-GD"),     xi18nc("@info: country code", "English (Grenada)")                                               },
    { QLatin1String("en-GH"),     xi18nc("@info: country code", "English (Ghana)")                                                 },
    { QLatin1String("en-GI"),     xi18nc("@info: country code", "English (Gibraltar)")                                             },
    { QLatin1String("en-GM"),     xi18nc("@info: country code", "English (Gambia)")                                                },
    { QLatin1String("en-GU"),     xi18nc("@info: country code", "English (Guam)")                                                  },
    { QLatin1String("en-GY"),     xi18nc("@info: country code", "English (Guyana)")                                                },
    { QLatin1String("en-IE"),     xi18nc("@info: country code", "English (Ireland)")                                               },
    { QLatin1String("en-IL"),     xi18nc("@info: country code", "English (Israel)")                                                },
    { QLatin1String("en-IN"),     xi18nc("@info: country code", "English (India)")                                                 },
    { QLatin1String("en-IO"),     xi18nc("@info: country code", "English (British Indian Ocean Territ)")                           },
    { QLatin1String("en-JM"),     xi18nc("@info: country code", "English (Jamaica)")                                               },
    { QLatin1String("en-KR"),     xi18nc("@info: country code", "English (Kenya)")                                                 },
    { QLatin1String("en-KI"),     xi18nc("@info: country code", "English (Kiribati)")                                              },
    { QLatin1String("en-KN"),     xi18nc("@info: country code", "English (St. Kitts-Nevis)")                                       },
    { QLatin1String("en-KY"),     xi18nc("@info: country code", "English (Cayman Islands)")                                        },
    { QLatin1String("en-LC"),     xi18nc("@info: country code", "English (St. Lucia)")                                             },
    { QLatin1String("en-LR"),     xi18nc("@info: country code", "English (Liberia)")                                               },
    { QLatin1String("en-LS"),     xi18nc("@info: country code", "English (Lesotho)")                                               },
    { QLatin1String("en-MP"),     xi18nc("@info: country code", "English (Northern Mariana Islands)")                              },
    { QLatin1String("en-MS"),     xi18nc("@info: country code", "English (Montserrat)")                                            },
    { QLatin1String("en-MT"),     xi18nc("@info: country code", "English (Malta)")                                                 },
    { QLatin1String("en-MU"),     xi18nc("@info: country code", "English (Mauritius)")                                             },
    { QLatin1String("en-MW"),     xi18nc("@info: country code", "English (Malawi)")                                                },
    { QLatin1String("en-MY"),     xi18nc("@info: country code", "English (Malaysia)")                                              },
    { QLatin1String("en-NA"),     xi18nc("@info: country code", "English (Namibia)")                                               },
    { QLatin1String("en-NF"),     xi18nc("@info: country code", "English (Norfolk Island)")                                        },
    { QLatin1String("en-NG"),     xi18nc("@info: country code", "English (Nigeria)")                                               },
    { QLatin1String("en-NR"),     xi18nc("@info: country code", "English (Nauru)")                                                 },
    { QLatin1String("en-NU"),     xi18nc("@info: country code", "English (Niue)")                                                  },
    { QLatin1String("en-NZ"),     xi18nc("@info: country code", "English (New Zealand)")                                           },
    { QLatin1String("en-PG"),     xi18nc("@info: country code", "English (Papua New Guinea)")                                      },
    { QLatin1String("en-PH"),     xi18nc("@info: country code", "English (Philippines)")                                           },
    { QLatin1String("en-PK"),     xi18nc("@info: country code", "English (Pakistan)")                                              },
    { QLatin1String("en-PN"),     xi18nc("@info: country code", "English (Pitcairn)")                                              },
    { QLatin1String("en-PR"),     xi18nc("@info: country code", "English (Puerto Rico)")                                           },
    { QLatin1String("en-PW"),     xi18nc("@info: country code", "English (Palau)")                                                 },
    { QLatin1String("en-RW"),     xi18nc("@info: country code", "English (Rwanda)")                                                },
    { QLatin1String("en-SB"),     xi18nc("@info: country code", "English (Solomon Islands)")                                       },
    { QLatin1String("en-SC"),     xi18nc("@info: country code", "English (Seychelles)")                                            },
    { QLatin1String("en-SG"),     xi18nc("@info: country code", "English (Singapore)")                                             },
    { QLatin1String("en-SH"),     xi18nc("@info: country code", "English (St. Helena)")                                            },
    { QLatin1String("en-SL"),     xi18nc("@info: country code", "English (Sierra Leone)")                                          },
    { QLatin1String("en-SO"),     xi18nc("@info: country code", "English (Somalia)")                                               },
    { QLatin1String("en-SZ"),     xi18nc("@info: country code", "English (Swaziland)")                                             },
    { QLatin1String("en-TC"),     xi18nc("@info: country code", "English (Turks and Caicos Islands)")                              },
    { QLatin1String("en-TK"),     xi18nc("@info: country code", "English (Tokelau)")                                               },
    { QLatin1String("en-TO"),     xi18nc("@info: country code", "English (Tonga)")                                                 },
    { QLatin1String("en-TT"),     xi18nc("@info: country code", "English (Trinidad)")                                              },
    { QLatin1String("en-UG"),     xi18nc("@info: country code", "English (Uganda)")                                                },
    { QLatin1String("en-US"),     xi18nc("@info: country code", "English (United States)")                                         },
    { QLatin1String("en-VC"),     xi18nc("@info: country code", "English (St. Vincent and the Grenadi)")                           },
    { QLatin1String("en-VG"),     xi18nc("@info: country code", "English (British Virgin Islands)")                                },
    { QLatin1String("en-VI"),     xi18nc("@info: country code", "English (U.S. Virgin Islands)")                                   },
    { QLatin1String("en-VU"),     xi18nc("@info: country code", "English (Vanuatu)")                                               },
    { QLatin1String("en-WS"),     xi18nc("@info: country code", "English (Western Samoa)")                                         },
    { QLatin1String("en-ZA"),     xi18nc("@info: country code", "English (South Africa)")                                          },
    { QLatin1String("en-ZM"),     xi18nc("@info: country code", "English (Zambia)")                                                },
    { QLatin1String("en-ZW"),     xi18nc("@info: country code", "English (Zimbabwe)")                                              },
    { QLatin1String("eo-FR"),     xi18nc("@info: country code", "Esperanto (France)")                                              },
    { QLatin1String("es-AR"),     xi18nc("@info: country code", "Spanish (Argentina)")                                             },
    { QLatin1String("es-BO"),     xi18nc("@info: country code", "Spanish (Bolivia)")                                               },
    { QLatin1String("es-CL"),     xi18nc("@info: country code", "Spanish (Chile)")                                                 },
    { QLatin1String("es-CO"),     xi18nc("@info: country code", "Spanish (Colombia)")                                              },
    { QLatin1String("es-CR"),     xi18nc("@info: country code", "Spanish (Costa Rica)")                                            },
    { QLatin1String("es-CU"),     xi18nc("@info: country code", "Spanish (Cuba)")                                                  },
    { QLatin1String("es-DO"),     xi18nc("@info: country code", "Spanish (Dominican Republic)")                                    },
    { QLatin1String("es-EC"),     xi18nc("@info: country code", "Spanish (Ecuador)")                                               },
    { QLatin1String("es-ES"),     xi18nc("@info: country code", "Spanish (Spain)")                                                 },
    { QLatin1String("es-GQ"),     xi18nc("@info: country code", "Spanish (Equatorial Guinea)")                                     },
    { QLatin1String("es-GT"),     xi18nc("@info: country code", "Spanish (Guatemala)")                                             },
    { QLatin1String("es-HN"),     xi18nc("@info: country code", "Spanish (Honduras)")                                              },
    { QLatin1String("es-MX"),     xi18nc("@info: country code", "Spanish (Mexico)")                                                },
    { QLatin1String("es-NI"),     xi18nc("@info: country code", "Spanish (Nicaragua)")                                             },
    { QLatin1String("es-PA"),     xi18nc("@info: country code", "Spanish (Panama)")                                                },
    { QLatin1String("es-PE"),     xi18nc("@info: country code", "Spanish (Peru)")                                                  },
    { QLatin1String("es-PR"),     xi18nc("@info: country code", "Spanish (Puerto Rico)")                                           },
    { QLatin1String("es-PY"),     xi18nc("@info: country code", "Spanish (Paraguay)")                                              },
    { QLatin1String("es-SV"),     xi18nc("@info: country code", "Spanish (El Salvador)")                                           },
    { QLatin1String("es-US"),     xi18nc("@info: country code", "Spanish (United States)")                                         },
    { QLatin1String("es-UY"),     xi18nc("@info: country code", "Spanish (Uruguay)")                                               },
    { QLatin1String("es-VE"),     xi18nc("@info: country code", "Spanish (Venezuela)")                                             },
    { QLatin1String("et-EE"),     xi18nc("@info: country code", "Estonian (Estonia)")                                              },
    { QLatin1String("eu-ES"),     xi18nc("@info: country code", "Basque (Basque Country)")                                         },
    { QLatin1String("fa-IR"),     xi18nc("@info: country code", "Persian (Iran)")                                                  },
    { QLatin1String("fi-FI"),     xi18nc("@info: country code", "Finnish (Finland)")                                               },
    { QLatin1String("fil-PH"),    xi18nc("@info: country code", "Filipino (Philippines)")                                          },
    { QLatin1String("fj-FJ"),     xi18nc("@info: country code", "Fijian (Fiji)")                                                   },
    { QLatin1String("fo-FO"),     xi18nc("@info: country code", "Faeroese (Faero Islands)")                                        },
    { QLatin1String("fr-AD"),     xi18nc("@info: country code", "French (Andorra)")                                                },
    { QLatin1String("fr-BE"),     xi18nc("@info: country code", "French (Belgium)")                                                },
    { QLatin1String("fr-BF"),     xi18nc("@info: country code", "French (Burkina Faso)")                                           },
    { QLatin1String("fr-BI"),     xi18nc("@info: country code", "French (Burundi)")                                                },
    { QLatin1String("fr-BJ"),     xi18nc("@info: country code", "French (Benin)")                                                  },
    { QLatin1String("fr-CA"),     xi18nc("@info: country code", "French (Canada)")                                                 },
    { QLatin1String("fr-CD"),     xi18nc("@info: country code", "French (Democratic Republic of Congo)")                           },
    { QLatin1String("fr-CF"),     xi18nc("@info: country code", "French (Central African Republic)")                               },
    { QLatin1String("fr-CG"),     xi18nc("@info: country code", "French (Congo)")                                                  },
    { QLatin1String("fr-CH"),     xi18nc("@info: country code", "French (Switzerland)")                                            },
    { QLatin1String("fr-CI"),     xi18nc("@info: country code", "French (Cote d'Ivoire)")                                          },
    { QLatin1String("fr-CM"),     xi18nc("@info: country code", "French (Cameroon)")                                               },
    { QLatin1String("fr-DJ"),     xi18nc("@info: country code", "French (Djibouti)")                                               },
    { QLatin1String("fr-FR"),     xi18nc("@info: country code", "French (France)")                                                 },
    { QLatin1String("fr-GA"),     xi18nc("@info: country code", "French (Gabon)")                                                  },
    { QLatin1String("fr-GB"),     xi18nc("@info: country code", "French (United Kingdom)")                                         },
    { QLatin1String("fr-GF"),     xi18nc("@info: country code", "French (French Guiana)")                                          },
    { QLatin1String("fr-GN"),     xi18nc("@info: country code", "French (Guinea)")                                                 },
    { QLatin1String("fr-GP"),     xi18nc("@info: country code", "French (Guadeloupe)")                                             },
    { QLatin1String("fr-HT"),     xi18nc("@info: country code", "French (Haiti)")                                                  },
    { QLatin1String("fr-IT"),     xi18nc("@info: country code", "French (Italy)")                                                  },
    { QLatin1String("fr-KM"),     xi18nc("@info: country code", "French (Comoros Islands)")                                        },
    { QLatin1String("fr-LB"),     xi18nc("@info: country code", "French (Lebanon)")                                                },
    { QLatin1String("fr-LU"),     xi18nc("@info: country code", "French (Luxembourg)")                                             },
    { QLatin1String("fr-MC"),     xi18nc("@info: country code", "French (Monaco)")                                                 },
    { QLatin1String("fr-MG"),     xi18nc("@info: country code", "French (Madagascar)")                                             },
    { QLatin1String("fr-ML"),     xi18nc("@info: country code", "French (Mali)")                                                   },
    { QLatin1String("fr-MQ"),     xi18nc("@info: country code", "French (Martinique)")                                             },
    { QLatin1String("fr-NC"),     xi18nc("@info: country code", "French (New Caledonia)")                                          },
    { QLatin1String("fr-PF"),     xi18nc("@info: country code", "French (French Polynesia)")                                       },
    { QLatin1String("fr-PM"),     xi18nc("@info: country code", "French (St. Pierre and Miquelon)")                                },
    { QLatin1String("fr-RE"),     xi18nc("@info: country code", "French (Reunion)")                                                },
    { QLatin1String("fr-RW"),     xi18nc("@info: country code", "French (Rwanda)")                                                 },
    { QLatin1String("fr-SC"),     xi18nc("@info: country code", "French (Seychelles)")                                             },
    { QLatin1String("fr-TD"),     xi18nc("@info: country code", "French (Chad)")                                                   },
    { QLatin1String("fr-TG"),     xi18nc("@info: country code", "French (Togo)")                                                   },
    { QLatin1String("fr-VU"),     xi18nc("@info: country code", "French (Vanuatu)")                                                },
    { QLatin1String("fr-WF"),     xi18nc("@info: country code", "French (Wallis and Futuna)")                                      },
    { QLatin1String("fr-YT"),     xi18nc("@info: country code", "French (Mayotte)")                                                },
    { QLatin1String("fy-NL"),     xi18nc("@info: country code", "Frisian (Netherlands)")                                           },
    { QLatin1String("ga-GB"),     xi18nc("@info: country code", "Irish (United Kingdom)")                                          },
    { QLatin1String("ga-IE"),     xi18nc("@info: country code", "Irish (Ireland)")                                                 },
    { QLatin1String("gd-GB"),     xi18nc("@info: country code", "Gaelic (United Kingdom)")                                         },
    { QLatin1String("gl-ES"),     xi18nc("@info: country code", "Galician (Galicia)")                                              },
    { QLatin1String("gu-IN"),     xi18nc("@info: country code", "Gujarati (India)")                                                },
    { QLatin1String("gv-GB"),     xi18nc("@info: country code", "Manx (United Kingdom)")                                           },
    { QLatin1String("ha-TD"),     xi18nc("@info: country code", "Hausa (Chad)")                                                    },
    { QLatin1String("haw-US"),    xi18nc("@info: country code", "Hawaiian (US state of Hawaii)")                                   },
    { QLatin1String("he-IL"),     xi18nc("@info: country code", "Modern Hebrew (Israel)")                                          },
    { QLatin1String("hi-IN"),     xi18nc("@info: country code", "Hindi (India)")                                                   },
    { QLatin1String("hmn-LA"),    xi18nc("@info: country code", "Hmong (Laos)")                                                    },
    { QLatin1String("hr-BA"),     xi18nc("@info: country code", "Croatian (Bosnia and Herzegovina, Latin)")                        },
    { QLatin1String("hr-HR"),     xi18nc("@info: country code", "Croatian (Croatia)")                                              },
    { QLatin1String("ht-FR"),     xi18nc("@info: country code", "Haitian Creole (France)")                                         },
    { QLatin1String("hu-HU"),     xi18nc("@info: country code", "Hungarian (Hungary)")                                             },
    { QLatin1String("hu-SI"),     xi18nc("@info: country code", "Hungarian (Slovenia)")                                            },
    { QLatin1String("hy-AM"),     xi18nc("@info: country code", "Armenian (Armenia)")                                              },
    { QLatin1String("id-ID"),     xi18nc("@info: country code", "Indonesian (Bahasa Indonesia)")                                   },
    { QLatin1String("ig-NG"),     xi18nc("@info: country code", "Igbo (Nigeria)")                                                  },
    { QLatin1String("ii-CN"),     xi18nc("@info: country code", "Sichuan Yi (People's Republic of China)")                         },
    { QLatin1String("is-IS"),     xi18nc("@info: country code", "Icelandic (Iceland)")                                             },
    { QLatin1String("it-CH"),     xi18nc("@info: country code", "Italian (Switzerland)")                                           },
    { QLatin1String("it-HR"),     xi18nc("@info: country code", "Italian (Croatia)")                                               },
    { QLatin1String("it-IT"),     xi18nc("@info: country code", "Italian (Italy)")                                                 },
    { QLatin1String("it-SI"),     xi18nc("@info: country code", "Italian (Slovenia)")                                              },
    { QLatin1String("it-SM"),     xi18nc("@info: country code", "Italian (San Marino)")                                            },
    { QLatin1String("iw-IL"),     xi18nc("@info: country code", "Hebrew (Israel)")                                                 },
    { QLatin1String("ja-JP"),     xi18nc("@info: country code", "Japanese (Japan)")                                                },
    { QLatin1String("jv-ID"),     xi18nc("@info: country code", "Modern Javanese (Indonesia)")                                     },
    { QLatin1String("jw-ID"),     xi18nc("@info: country code", "Javanese (Indonesia)")                                            },
    { QLatin1String("ka-GE"),     xi18nc("@info: country code", "Georgian (Georgia)")                                              },
    { QLatin1String("kk-KZ"),     xi18nc("@info: country code", "Kazakh (Kazakhstan)")                                             },
    { QLatin1String("kl-GL"),     xi18nc("@info: country code", "Greenlandic (Greenland)")                                         },
    { QLatin1String("km-KH"),     xi18nc("@info: country code", "Khmer (Cambodia)")                                                },
    { QLatin1String("kn-IN"),     xi18nc("@info: country code", "Kannada (India)")                                                 },
    { QLatin1String("ko-KR"),     xi18nc("@info: country code", "Korean (South Korea)")                                            },
    { QLatin1String("ko-KP"),     xi18nc("@info: country code", "Korean (North Korea)")                                            },
    { QLatin1String("ky-KG"),     xi18nc("@info: country code", "Kyrgyz (Kyrgyzstan)")                                             },
    { QLatin1String("ku-IR"),     xi18nc("@info: country code", "Cornish (United Kingdom)")                                        },
    { QLatin1String("kw-GB"),     xi18nc("@info: country code", "Kurdish (Iran)")                                                  },
    { QLatin1String("la-IT"),     xi18nc("@info: country code", "Latin (Italy)")                                                   },
    { QLatin1String("lb-LU"),     xi18nc("@info: country code", "Luxembourgish (Luxembourg)")                                      },
    { QLatin1String("ln-CD"),     xi18nc("@info: country code", "Lingala (Democratic Republic of Congo)")                          },
    { QLatin1String("ln-CG"),     xi18nc("@info: country code", "Lingala (Congo)")                                                 },
    { QLatin1String("lo-LA"),     xi18nc("@info: country code", "Lao (Lao PDR)")                                                   },
    { QLatin1String("lt-LT"),     xi18nc("@info: country code", "Lithuanian (Lithuania)")                                          },
    { QLatin1String("lv-LV"),     xi18nc("@info: country code", "Latvian (Latvia)")                                                },
    { QLatin1String("mg-MG"),     xi18nc("@info: country code", "Malagasy (Madagascar)")                                           },
    { QLatin1String("mhr-RU"),    xi18nc("@info: country code", "Meadow Mari (Russia)")                                            },
    { QLatin1String("mi-NZ"),     xi18nc("@info: country code", "Maori (New Zealand)")                                             },
    { QLatin1String("mk-MK"),     xi18nc("@info: country code", "Macedonian (Macedonia)")                                          },
    { QLatin1String("ml-IN"),     xi18nc("@info: country code", "Malayalam (India)")                                               },
    { QLatin1String("mn-CN"),     xi18nc("@info: country code", "Mongolian (People's Republic of China)")                          },
    { QLatin1String("mn-MN"),     xi18nc("@info: country code", "Mongolian (Mongolia)")                                            },
    { QLatin1String("mr-IN"),     xi18nc("@info: country code", "Marathi (India)")                                                 },
    { QLatin1String("mrj-RU"),    xi18nc("@info: country code", "Hill Mari (Russia)")                                              },
    { QLatin1String("ms-BN"),     xi18nc("@info: country code", "Malay (Brunei Darussalam)")                                       },
    { QLatin1String("ms-MY"),     xi18nc("@info: country code", "Malay (Malaysia)")                                                },
    { QLatin1String("ms-SG"),     xi18nc("@info: country code", "Malay (Singapore)")                                               },
    { QLatin1String("mt-MT"),     xi18nc("@info: country code", "Maltese (Malta)")                                                 },
    { QLatin1String("my-MM"),     xi18nc("@info: country code", "Burmese (Myanmar)")                                               },
    { QLatin1String("nb-NO"),     xi18nc("@info: country code", "Norwegian Bokmål (Norway)")                                       },
    { QLatin1String("ne-NP"),     xi18nc("@info: country code", "Nepali (Nepal)")                                                  },
    { QLatin1String("nl-AN"),     xi18nc("@info: country code", "Dutch (Netherlands Antilles)")                                    },
    { QLatin1String("nl-AW"),     xi18nc("@info: country code", "Dutch (Aruba)")                                                   },
    { QLatin1String("nl-BE"),     xi18nc("@info: country code", "Dutch (Belgium)")                                                 },
    { QLatin1String("nl-NL"),     xi18nc("@info: country code", "Dutch (Netherlands)")                                             },
    { QLatin1String("nl-SR"),     xi18nc("@info: country code", "Dutch (Suriname)")                                                },
    { QLatin1String("no-NO"),     xi18nc("@info: country code", "Norwegian (Norway)")                                              },
    { QLatin1String("nn-NO"),     xi18nc("@info: country code", "Norwegian Nynorsk (Norway)")                                      },
    { QLatin1String("ns-ZA"),     xi18nc("@info: country code", "Sesotho sa Leboa (South Africa)")                                 },
    { QLatin1String("ny-ZM"),     xi18nc("@info: country code", "Chewa (Zambia)")                                                  },
    { QLatin1String("oc-FR"),     xi18nc("@info: country code", "Occitan (France)")                                                },
    { QLatin1String("or-IN"),     xi18nc("@info: country code", "Oriya (India)")                                                   },
    { QLatin1String("pa-IN"),     xi18nc("@info: country code", "Punjabi (India)")                                                 },
    { QLatin1String("pap-AW"),    xi18nc("@info: country code", "Papiamento (Aruba-Dutch Caribbean)")                              },
    { QLatin1String("pl-PL"),     xi18nc("@info: country code", "Polish (Poland)")                                                 },
    { QLatin1String("ps-AF"),     xi18nc("@info: country code", "Pashto (Afghanistan)")                                            },
    { QLatin1String("pt-AO"),     xi18nc("@info: country code", "Portuguese (Angola)")                                             },
    { QLatin1String("pt-BR"),     xi18nc("@info: country code", "Portuguese (Brazil)")                                             },
    { QLatin1String("pt-CV"),     xi18nc("@info: country code", "Portuguese (Cape Verde Islands)")                                 },
    { QLatin1String("pt-GW"),     xi18nc("@info: country code", "Portuguese (Guinea-Bissau)")                                      },
    { QLatin1String("pt-MZ"),     xi18nc("@info: country code", "Portuguese (Mozambique)")                                         },
    { QLatin1String("pt-PT"),     xi18nc("@info: country code", "Portuguese (Portugal)")                                           },
    { QLatin1String("pt-ST"),     xi18nc("@info: country code", "Portuguese (São Tomé e Principe)")                                },
    { QLatin1String("otq-MX"),    xi18nc("@info: country code", "Otomi Querétaro (Mexico)")                                        },
    { QLatin1String("rm-CH"),     xi18nc("@info: country code", "Romansh (Switzerland)")                                           },
    { QLatin1String("ro-RO"),     xi18nc("@info: country code", "Romanian (Romania)")                                              },
    { QLatin1String("ru-RU"),     xi18nc("@info: country code", "Russian (Russia)")                                                },
    { QLatin1String("rw-RW"),     xi18nc("@info: country code", "Kinyarwanda (Rwanda)")                                            },
    { QLatin1String("sa-IN"),     xi18nc("@info: country code", "Sanskrit (India)")                                                },
    { QLatin1String("sd-IN"),     xi18nc("@info: country code", "Sindhi (India)")                                                  },
    { QLatin1String("sd-PK"),     xi18nc("@info: country code", "Sindhi (Pakistan)")                                               },
    { QLatin1String("se-FI"),     xi18nc("@info: country code", "Sami (Northern, Finland)")                                        },
    { QLatin1String("se-NO"),     xi18nc("@info: country code", "Sami (Northern, Norway)")                                         },
    { QLatin1String("se-SE"),     xi18nc("@info: country code", "Sami (Northern, Sweden)")                                         },
    { QLatin1String("si-LK"),     xi18nc("@info: country code", "Sinhala (Sri Lanka)")                                             },
    { QLatin1String("sk-SK"),     xi18nc("@info: country code", "Slovak (Slovakia)")                                               },
    { QLatin1String("sl-SI"),     xi18nc("@info: country code", "Slovenian (Slovenia)")                                            },
    { QLatin1String("sm-WS"),     xi18nc("@info: country code", "Samoan (Samoa)")                                                  },
    { QLatin1String("sn-ZW"),     xi18nc("@info: country code", "Shona (Zimbabwe)")                                                },
    { QLatin1String("so-SO"),     xi18nc("@info: country code", "Somali  (Somalia)")                                               },
    { QLatin1String("sq-AL"),     xi18nc("@info: country code", "Albanian (Albania)")                                              },
    { QLatin1String("sr-BA"),     xi18nc("@info: country code", "Serbian (Bosnia-Herzegovina)")                                    },
    { QLatin1String("sr-RS"),     xi18nc("@info: country code", "Serbian (Serbia)")                                                },
    { QLatin1String("sr-SP"),     xi18nc("@info: country code", "Serbian (Serbia and Montenegro)")                                 },
    { QLatin1String("sr-YU"),     xi18nc("@info: country code", "Serbian (Yugoslavia)")                                            },
    { QLatin1String("ss-SZ"),     xi18nc("@info: country code", "Swati (Swaziland)")                                               },
    { QLatin1String("ss-ZA"),     xi18nc("@info: country code", "Swati (South Africa)")                                            },
    { QLatin1String("st-LS"),     xi18nc("@info: country code", "Sotho (Lesotho)")                                                 },
    { QLatin1String("su-ID"),     xi18nc("@info: country code", "Sundanese (Indonesia)")                                           },
    { QLatin1String("sv-FI"),     xi18nc("@info: country code", "Swedish (Finland)")                                               },
    { QLatin1String("sv-SE"),     xi18nc("@info: country code", "Swedish (Sweden)")                                                },
    { QLatin1String("sw-KE"),     xi18nc("@info: country code", "Swahili (Kenya)")                                                 },
    { QLatin1String("sw-TZ"),     xi18nc("@info: country code", "Swahili (Tanzania)")                                              },
    { QLatin1String("ta-IN"),     xi18nc("@info: country code", "Tamil (India)")                                                   },
    { QLatin1String("ta-SG"),     xi18nc("@info: country code", "Tamil (Singapore)")                                               },
    { QLatin1String("te-IN"),     xi18nc("@info: country code", "Telugu (India)")                                                  },
    { QLatin1String("tg-TJ"),     xi18nc("@info: country code", "Tajik (Tajikistan)")                                              },
    { QLatin1String("th-TH"),     xi18nc("@info: country code", "Thai (Thailand)")                                                 },
    { QLatin1String("tk-TM"),     xi18nc("@info: country code", "Turkmen (Turkmenistan)")                                          },
    { QLatin1String("tlh-US"),    xi18nc("@info: country code", "Klingon (US state)")                                              },
    { QLatin1String("tl-PH"),     xi18nc("@info: country code", "Tagalog (Philippines)")                                           },
    { QLatin1String("tn-BW"),     xi18nc("@info: country code", "Setswana Tswana (Botswana)")                                      },
    { QLatin1String("tn-ZA"),     xi18nc("@info: country code", "Setswana Tswana (South Africa)")                                  },
    { QLatin1String("to-TO"),     xi18nc("@info: country code", "Tongan (Tonga)")                                                  },
    { QLatin1String("tr-BG"),     xi18nc("@info: country code", "Turkish (Bulgaria)")                                              },
    { QLatin1String("tr-CY"),     xi18nc("@info: country code", "Turkish (Cyprus)")                                                },
    { QLatin1String("tr-TR"),     xi18nc("@info: country code", "Turkish (Turkey)")                                                },
    { QLatin1String("tt-RU"),     xi18nc("@info: country code", "Tatar (Russia)")                                                  },
    { QLatin1String("ty-PF"),     xi18nc("@info: country code", "Tahitian (French Polynesia)")                                     },
    { QLatin1String("udm-RU"),    xi18nc("@info: country code", "Udmurt (Russia)")                                                 },
    { QLatin1String("ug-CN"),     xi18nc("@info: country code", "Uighur (People's Republic of China)")                             },
    { QLatin1String("uk-UA"),     xi18nc("@info: country code", "Ukrainian (Ukraine)")                                             },
    { QLatin1String("ur-IN"),     xi18nc("@info: country code", "Urdu (India)")                                                    },
    { QLatin1String("ur-PK"),     xi18nc("@info: country code", "Urdu (Pakistan)")                                                 },
    { QLatin1String("uz-UZ"),     xi18nc("@info: country code", "Uzbek (Uzbekistan)")                                              },
    { QLatin1String("vi-VN"),     xi18nc("@info: country code", "Vietnamese (Vietnam)")                                            },
    { QLatin1String("wo-SN"),     xi18nc("@info: country code", "Wolof (Senegal)")                                                 },
    { QLatin1String("xh-ZA"),     xi18nc("@info: country code", "IsiXhosa Xhosa (South Africa)")                                   },
    { QLatin1String("yi-DE"),     xi18nc("@info: country code", "Yiddish (Germany)")                                               },
    { QLatin1String("yo-NG"),     xi18nc("@info: country code", "Yoruba (Nigeria)")                                                },
    { QLatin1String("yua-MX"),    xi18nc("@info: country code", "Yucatec Maya (Mexico)")                                           },
    { QLatin1String("zh-CN"),     xi18nc("@info: country code", "Chinese (People's Republic of China)")                            },
    { QLatin1String("zh-HK"),     xi18nc("@info: country code", "Chinese (Hong Kong SAR, People's Republic of China)")             },
    { QLatin1String("zh-MO"),     xi18nc("@info: country code", "Chinese (Macao SAR)")                                             },
    { QLatin1String("zh-SG"),     xi18nc("@info: country code", "Chinese (Singapore)")                                             },
    { QLatin1String("zh-TW"),     xi18nc("@info: country code", "Chinese (Taiwan)")                                                },
    { QLatin1String("zn-CH"),     xi18nc("@info: country code", "Simplified Chinese (People's Republic of China)")                 },
    { QLatin1String("zu-ZA"),     xi18nc("@info: country code", "isiZulu Zulu (South Africa)")                                     }
};

} // namespace Digikam
